name: Release

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: write
            pull-requests: read
        steps:
            - uses: actions/checkout@v2

            - name: Write raw version to env
              run: |
                  echo "VERSION=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"
            - name: Substitute version in manifest
              uses: microsoft/variable-substitution@v1
              with:
                  files: 'system/system.json'
              env:
                  version: ${{ env.VERSION }}
                  download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/system.zip

            - name: Install dependencies and build
              run: |
                  npm ci
                  npm run build

            - name: Create system zip
              run: zip -r system.zip dist/* LICENSE README.md
            - name: Update release with files
              uses: ncipollo/release-action@v1
              with:
                  allowUpdates: true
                  name: ${{ github.event.release.name }}
                  draft: false
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifacts: 'dist/system.json,system.zip'
                  tag: ${{ github.event.release.tag_name }}
                  body: ${{ github.event.release.body }}
